import { useGenerateReport } from '../hooks/useQueries';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Download, TrendingDown, Sparkles } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { toast } from 'sonner';

export default function ReportModule() {
  const { data: report, isLoading } = useGenerateReport();

  const handleDownload = () => {
    if (!report) return;

    const reportText = `
AI PROMPT OPTIMIZATION SUITE - IMPACT REPORT
Generated: ${new Date().toLocaleString()}

========================================
SUMMARY
========================================
Total Optimizations: ${report.optimizations.length}
Total CO₂ Savings: ${report.totalSavings.toFixed(6)} kg

========================================
PROMPT OPTIMIZATIONS (${report.optimizations.length})
========================================
${report.optimizations
  .map(
    (opt, i) => `
${i + 1}. Optimization
   Date: ${new Date(Number(opt.timestamp) / 1000000).toLocaleString()}
   Original Length: ${opt.originalLength} chars
   Optimized Length: ${opt.optimizedLength} chars
   Reduction: ${Number(opt.originalLength) - Number(opt.optimizedLength)} chars
   CO₂ Savings: ${opt.estimatedSavings.toFixed(6)} kg
   
   Original: ${opt.originalPrompt}
   Optimized: ${opt.optimizedPrompt}
`
  )
  .join('\n')}

========================================
Generated by AI Prompt Optimization Suite
Built with caffeine.ai
========================================
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-optimization-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Report downloaded successfully!');
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-64 w-full" />
        <Skeleton className="h-96 w-full" />
      </div>
    );
  }

  if (!report || report.optimizations.length === 0) {
    return (
      <Card className="border-emerald-200 bg-white/80 backdrop-blur-sm dark:border-emerald-800 dark:bg-emerald-900/30">
        <CardContent className="flex flex-col items-center justify-center py-12">
          <FileText className="mb-4 h-16 w-16 text-emerald-400 dark:text-emerald-600" />
          <p className="text-center text-emerald-700 dark:text-emerald-300">
            No optimizations yet. Start optimizing prompts to generate reports!
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="mb-2 text-3xl font-bold text-emerald-900 dark:text-emerald-100">Impact Report</h2>
          <p className="text-emerald-700 dark:text-emerald-300">
            Comprehensive summary of your prompt optimization metrics
          </p>
        </div>
        <Button
          onClick={handleDownload}
          className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white hover:from-emerald-700 hover:to-teal-700"
        >
          <Download className="mr-2 h-4 w-4" />
          Download Report
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card className="border-emerald-200 bg-white/80 backdrop-blur-sm dark:border-emerald-800 dark:bg-emerald-900/30">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-emerald-700 dark:text-emerald-300">
              Total Optimizations
            </CardTitle>
            <Sparkles className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-emerald-900 dark:text-emerald-100">
              {report.optimizations.length}
            </div>
            <p className="text-xs text-emerald-600 dark:text-emerald-400">Prompts optimized</p>
          </CardContent>
        </Card>

        <Card className="border-emerald-200 bg-white/80 backdrop-blur-sm dark:border-emerald-800 dark:bg-emerald-900/30">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-emerald-700 dark:text-emerald-300">
              Total CO₂ Savings
            </CardTitle>
            <TrendingDown className="h-4 w-4 text-teal-600 dark:text-teal-400" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-emerald-900 dark:text-emerald-100">
              {report.totalSavings.toFixed(6)}
            </div>
            <p className="text-xs text-teal-600 dark:text-teal-400">kg CO₂</p>
          </CardContent>
        </Card>
      </div>

      <Card className="border-emerald-200 bg-white/80 backdrop-blur-sm dark:border-emerald-800 dark:bg-emerald-900/30">
        <CardHeader>
          <CardTitle className="text-emerald-900 dark:text-emerald-100">Optimizations Summary</CardTitle>
          <CardDescription className="text-emerald-600 dark:text-emerald-400">
            {report.optimizations.length} total optimizations
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {report.optimizations.slice(0, 10).map((opt) => (
              <div
                key={opt.id}
                className="flex items-center justify-between border-b border-emerald-200 pb-2 dark:border-emerald-800"
              >
                <div className="flex-1">
                  <p className="truncate font-medium text-emerald-900 dark:text-emerald-100">
                    {opt.originalPrompt.substring(0, 50)}...
                  </p>
                  <p className="text-sm text-emerald-600 dark:text-emerald-400">
                    {Number(opt.originalLength)} → {Number(opt.optimizedLength)} chars (
                    {Math.round(
                      ((Number(opt.originalLength) - Number(opt.optimizedLength)) / Number(opt.originalLength)) * 100
                    )}
                    % reduction)
                  </p>
                </div>
                <div className="text-right">
                  <p className="font-semibold text-teal-600 dark:text-teal-400">
                    -{opt.estimatedSavings.toFixed(6)} kg
                  </p>
                  <p className="text-xs text-emerald-600 dark:text-emerald-400">CO₂ saved</p>
                </div>
              </div>
            ))}
            {report.optimizations.length > 10 && (
              <p className="text-center text-sm text-emerald-600 dark:text-emerald-400">
                +{report.optimizations.length - 10} more optimizations
              </p>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
